{% set name = "bmad" %}
{% set version = "2021_0525" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bmad-sim/bmad_distribution/releases/download/bmad_dist_{{ version }}/bmad_dist_{{ version }}.tgz
  sha256: 9f9005216b9660ebdb4e4be60c2a07e8d7f14fd9dadd64b068ed5f6248c194fe
  patches:
    - 0001-bmad_conda_install.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
    - make
    - automake
    - autoconf
    - libtool
    - m4
    - pkg-config   # [osx]
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - readline
    - ncurses
    - cairo
    - pango
    - xorg-libxt
    - pgplot
    - hdf5
    - hdf5-static  # [osx]
    - xorg-libx11
    - xorg-xproto
    - fftw
    - blas
    - lapack
    - lapack95
    - gsl =2.4
    - xraylib
  run:
    - readline
    - ncurses
    - cairo
    - pango
    - xorg-libxt
    - pgplot
    - hdf5
    - hdf5-static  # [osx]
    - fftw
    - lapack
    - lapack95
    - gsl =2.4
    - xraylib
    - xorg-libx11
    - xorg-xproto
    - libopenblas
    - libcblas

test:
  commands:
    - tao -help

about:
  home: https://www.classe.cornell.edu/bmad
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: bmad/Copyright
  summary: 'Bmad is an object oriented, open source, subroutine library for relativistic charged-particle dynamics simulations in accelerators and storage rings.'
  description: |
    Bmad has been developed at Cornell University's Laboratory for Elementary
    Particle Physics and has been in use since the mid 1990s.
    Bmad has a wide range of routines to do many things.
    Bmad can be used to study both single and multi-particle
    beam dynamics. It has routines to track both particles and
    macroparticles. Bmad has various tracking algorithms including
    Runge-Kutta and symplectic (Lie algebraic) integration.
    Wakefields, and radiation excitation and damping can be simulated.
    Bmad has routines for calculating transfer matrices, emittances,
    Twiss parameters, dispersion, coupling, etc.
  doc_url: https://www.classe.cornell.edu/bmad/manual.html

extra:
  recipe-maintainers:
    - hhslepicka
    - ChristopherMayes
